set mouse=
filetype plugin indent on
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
set directory^=$HOME/.vim/tmp//
" syntax off
set nohlsearch
set t_Co=0

